### ISSUE TITLE
Migrate existing tests to node-tap

### ISSUE THREAD

**Issue by aqrln** [metarhia/jstp#145]
The consensus is we should use `node-tap` as the test framework instead of `mocha` and `chai`. This may be a gradual and incremental process.
We'll need to migrate:
* [x] serde (#153)
* [x] message parser (#168)
* [x] errors (#167)
* [x] connection (#183, #198, #199, #200)
* [x] remote proxy (#198, #199)
* [x] client (#183, #198)
* [x] server (#183)

**Comment by nechaido** [comment]
We'll need to migrate:
* [x] serde (#153)
* [ ] message parser
* [ ] errors
* [ ] connection
* [ ] remote proxy
* [ ] client
* [ ] server
