### ISSUE TITLE
Test W3C WebSocket transport

### ISSUE THREAD

**Issue by aqrln** [metarhia/jstp#148]
Now we use Karma to run the same unit tests that we run in Node, which is kinda useless. To the contrary, the browser WebSocket transport is not tested at all, while it must be.

**Comment by nechaido** [comment]
Which testing framework will we use for this purpose?

**Comment by nechaido** [comment]
Closed in https://github.com/metarhia/jstp/commit/aea9cba60d560ae76deb244dd76dac38958f4778. 
PR-URL: https://github.com/metarhia/jstp/pull/268.
