### ISSUE TITLE
Use ES5.1 getters syntax in JSTP Object Serialization

### ISSUE THREAD

**Issue by aqrln** [metarhia/JSTP#15]
In my opinion, objects serialized via JSTP must be anemic structures and there should be no random functions, only very simple getters. So it might be better to use the concise syntax introduced in ES5.

**Comment by tshemsedinov** [comment]
As we discussed this spring, we should have 3 levels of parsers: (1) Array data, (2) Anemic objects, (3) Rich JSTP including: data, metadata, expressions, constructors, functions, getters/setters. We need 3rd format to store and transmit metadata/schemas. But regular interactions will be in 1st format.

**Comment by tshemsedinov** [comment]
2nd format may be used for: configurations, any readable structures in code, some packets if we have no schemas.

**Comment by nechaido** [comment]
Closed during to #160
