### ISSUE TITLE
Rewrite JSTP Record Serialization in C++

### ISSUE THREAD

**Issue by aqrln** [metarhia/JSTP#16]
Given the same object and 100000 iterations:

* `JSON.stringify` — 134.377 ms
* `JSON.parse` — 201.747 ms
* `jstp.stringify` — 492.840 ms (3.67x slower than JSON)
* `jstp.parse` (naive three-line implementation) — 45634.546 ms (226.2x slower than JSON)
* `jstp.parse` (secure implementation with validation and timeouts) — 61266.695 ms (303.68x slower than JSON)
* `jstp.parse` (no validation, shared sandbox) — 5449 ms (27x slower than JSON)
* `jstp.parse` (validation, shared sandbox) — 9011.31 ms (44.67x slower than JSON)

We have an efficient implementation of the parser and serializer in C++, it must be rewritten using V8 data types and integrated into this library.

**Update:** the prototype of a parser as a native Node.js addon gives the following results:

* `json.stringify` — N/A (not finished yet)
* `json.parse` — 652.148 ms (3.23x slower than JSON, 13.82x faster than our most recent version of the JavaScript parser)

**Comment by tshemsedinov** [comment]
I believe we can do that in js and I have got contrary results this spring

**Comment by tshemsedinov** [comment]
1. @aqrln we need `jstp.parse` just for metadata/schemas "full" objects with fields and functions.
2. We will use arrays as a common data format, so each [protocol](https://github.com/metarhia/JSTP/blob/master/docs/protocol.md) packet should not be parsed using `jstp.parse`, we can do that with specialized string-operations parser.
3. I remember that creating sandboxes is much more heavy operation, so we may `createContext` once for each connection.
4. We can also change `runInNewContext` to `runInThisContext` and will get speed close to JSON.

**Comment by tshemsedinov** [comment]
I propose to implement it ASAP in C++ and JS and compare @aqrln @belochub

**Comment by aqrln** [comment]
@tshemsedinov 
1. According to our summer specs, that's what's `jstp.interprete` for while `jstp.parse` is for pure data structures without functions.
4. We will not. JSON is a very low-level part of V8 that is optimized almost to a single instruction. It is theoretically possible to achieve a similar speed in a native addon (though it will require a great deal of work), but V8's JavaScript parser is more complex and much slower that JSON parser.

**Comment by aqrln** [comment]
@tshemsedinov 
> I propose to implement it ASAP in C++ and JS and compare @aqrln @belochub
Okay, that is a reasonable idea and it is worth checking out. I think that a naive and quick implementation of parser in JavaScript might be even faster than in C++ (because of JavaScript's string operations optimizations and stuff) but an optimized parser in C++ should be faster.

**Comment by aqrln** [comment]
Also, the main bottleneck is actually creating sandboxes. Naive `jstp.parse` without validation and with one shared sandbox is only 27 times slower than JSON. It is actually still quite slow but not 226 times, on the other hand.

**Comment by aqrln** [comment]
@tshemsedinov returning to the previous post
> 2. We will use arrays as a common data format, so each protocol packet should not be parsed using jstp.parse, we can do that with specialized string-operations parser.

It will not work since the values inside that arrays may be random objects (and now they actually are, for example, in remote events).

**Comment by tshemsedinov** [comment]
@aqrln array format may contain just scalar and array, for example:
```js
{
  name: 'Marcus Aurelius',
  books: [
    {
      title: 'Meditations',
      written: 167
    }
  ]
}
```
will be converted to arrays: `['Marcus Aurelius',[['Meditations',167]]]`

**Comment by aqrln** [comment]
@tshemsedinov 
> I propose to implement it ASAP in C++ and JS and compare

BTW, we will need to implement a parser in JavaScript either way. It will be a part of browser JSTP implementation. Creating `iframe`s isn't a proper way of parsing network packets even though the prototype worked.
