### ISSUE TITLE
Remove JSOS

### ISSUE THREAD

**Issue by nechaido** [metarhia/JSTP#160]
As it was discussed we should remove support for Java Script Object Serialization format because there is no need for it. We`ll need to remove both:
* [ ] implementation (https://github.com/metarhia/JSTP/pull/170)
* [ ] tests (https://github.com/metarhia/JSTP/pull/170)

**Comment by lundibundi** [comment]
I guess we should also close this one https://github.com/metarhia/JSTP/issues/15?

**Comment by nechaido** [comment]
@lundibundi yep
