### ISSUE TITLE
Getting the port a server is bound to

### ISSUE THREAD

**Issue by nechaido** [metarhia/jstp#184]
We need an API to get a random free port.
At the moment I have two ways to write test:
* listen on `0` port, and get server port by accessing the rawServer
* use hardcoded values

Both are not ok. It would be great to be able to get a random free port.
Although, this feature may be prone to race condition.

**Comment by tshemsedinov** [comment]
Why do we need random ports? And for what reason? (maybe you propose it for tests)
Good ways to do that:
- environment variable
- configuration files (I'd prefer)
- command line parameters

@metarhia/jstp-core

**Comment by lundibundi** [comment]
Yes it's to be used in tests, at least for now (see https://github.com/metarhia/jstp/pull/183). 

And this may indeed be prone to race conditions but I do not think we'll be able to see it in this project as it requires some real lot amount of simultaneous network tests to be run. But to avoid them completely this should probably be some sort of separate service which will keep track of pending requests.

**Comment by lundibundi** [comment]
@aqrln I meant in case of implementing something different than using bind(0) =).

**Comment by tshemsedinov** [comment]
@aqrln ok, it's clear after renaming
