### ISSUE TITLE
Improper testing of NaN values

### ISSUE THREAD

**Issue by belochub** [metarhia/jstp#202]
At the moment json5 tests include testing for correct NaN value parsing, but this tests check NaN value equality using `strictSame` comparison, which does not work with NaN values.
`isNaN` function has to be used instead.

**Comment by nechaido** [comment]
At the point I have only one solution - writing custom function, that well check for deep equality: `deepEqual(value, expected)`
and test if it returns true: `test.assert(deepEqual(jstp.parse(value), expected)`

@metarhia/jstp what do you think?

**Comment by nechaido** [comment]
I say the best solution is: `npm install -save-dev lodash.isequal`
