### ISSUE TITLE
Unmatched README

### ISSUE THREAD

**Issue by thundernet8** [metarhia/jstp#235]
For the demo code in README of master branch, I run test of it, two issues:

1. `jstp.net.createServer` should be `jstp.tcp.createServer`, the `jstp.net` new api not implemented in the latest package

2. `function handleConnect(error, connection, app)` should  be `function handleConnect(error, connection, sid, app)`

I think the new API code has not been merged to master

**Comment by aqrln** [comment]
Hi and thanks for reaching out! The new API has already been merged to master as per b6e9eee0144ee03960454f769983acbcac65b90a (https://github.com/metarhia/jstp/pull/104) for the former issue and 7c351fbfe45b5f4dea383def6c2e01c44c9058d2 (https://github.com/metarhia/jstp/pull/209) for the latter one. I believe you are running the demo using the package from npm, not from the master branch. I have to admit that a mismatch between the API shown on the landing page of the project (which essentially a README is) and the actual API of the latest npm package is no less confusing though, so sorry for that. We are planning that the new version will have been released by the end of this month.

**Comment by thundernet8** [comment]
thanks, got it

**Comment by belochub** [comment]
As a temporal workaround while there is no new version of our package in npm, you can use the version from the git repository, by installing the package like this: `npm install metarhia/jstp`
