### ISSUE TITLE
Can we parse query syntax?

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/jstp#25]
```js
{
  name: 'Marcus',
  age > 20,
  city != 'Kiev'
}
```
or even
```js
{
  name = 'Marcus',
  country <> 'China',
  score: 200..500,
}
```
or even
```js
{
  name = 'Marcus',
  country ≠ 'China',
  score ∈ [200,500),
  city ∉ {'Kiev', 'Roma'}
}
```
It would be great to get something like following after parsing:
```js
{
  name: ['=', 'Marcus'],
  age: ['>', 20],
  score: ['>=', 200, '<', 500],
  city: ['Kiev', 'Roma']
}
```

**Comment by tshemsedinov** [comment]
No backward serialization needed

**Comment by aqrln** [comment]
@tshemsedinov do we still need this feature?

**Comment by tshemsedinov** [comment]
@aqrln arguable and not a priority now, let's leave it here as is

**Comment by tshemsedinov** [comment]
I think we will use different syntax for queries, not mixing it with JS or JSON5 for compatibility. So I propose to close this issue @aqrln, ok?
