### ISSUE TITLE
Use local variable instead of this

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/JSTP#26]
I think we have multiple problems:
https://github.com/metarhia/JSTP/blob/master/lib/server.js#L71
https://github.com/metarhia/JSTP/blob/master/lib/server.js#L90
https://github.com/metarhia/JSTP/blob/master/lib/server.js#L103
https://github.com/metarhia/JSTP/blob/master/lib/server.js#L64

Proposed fix:
```js
Server.prototype.getClients = function() {
  if (this._cachedClientsArray.length === 0) {
    var server = this; // FIX
    this._cachedClientsArray = Object.keys(this.clients).map(function(cid) {
      return server.clients[cid]; // FIX
    });
  }
  return this._cachedClientsArray;
};
```

**Comment by aqrln** [comment]
There's no such issue in https://github.com/metarhia/JSTP/blob/master/lib/server.js#L103 but the other places do have the problem indeed.
