### ISSUE TITLE
Drop excess Node versions from Travis build matrix

### ISSUE THREAD

**Issue by aqrln** [metarhia/jstp#262]
I'd advocate for testing only using the latest releases of Node.js 6.x, 7.x and 8.x on Travis. We use CI to find our bugs, not old and resolved Node bugs. What others think about it?

/cc @metarhia/jstp-core

**Comment by tshemsedinov** [comment]
Sure, I agree

**Comment by belochub** [comment]
@aqrln, is Node.js 7 still supported at the moment?
As far as I remember, it must've been supported only until the end of the previous month, and if that's the case, I don't think we should enable CI builds on Node.js 7.

**Comment by aqrln** [comment]
@belochub Node.js 7 is unsupported, right. However, I believe a fair amount of people might still be using it. I am okay with both keeping and dropping it from the CI environment.
