### ISSUE TITLE
Hearbeat messages not delivered before HANDSHAKE_TIMEOUT

### ISSUE THREAD

**Issue by aqrln** [metarhia/jstp#283]
~~Handshake~~ Heartbeat messages don't start flowing until `HANDSHAKE_TIMEOUT` interval (that is, 3 seconds) is passed.

**Comment by belochub** [comment]
@aqrln, can you provide more information on this issue, steps to reproduce, maybe?
I wasn't able to reproduce this on the current `master` branch.

**Comment by aqrln** [comment]
@belochub sorry for the late reply. I didn't provide a reproduction because I left this issue for myself, actually. It was found during investigation of #217 and I'm going to open a PR that fixes both issues at once.

**Comment by aqrln** [comment]
Sorry, I now understand your confusion. "Handshake" was a typo, I meant "heartbeat".
