### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dmytro-khara** [metarhia/JSTP#29]
Kubuntu 14.04 
npm 3.10.9
node v6.9.2
Npm log is attached
[npm-debug.txt](https://github.com/metarhia/JSTP/files/644645/npm-debug.txt)

**Comment by aqrln** [comment]
Make sure that you have C++ compiler, `make` and other development tools installed on your machine (run `sudo apt-get install build-essential` if not). If you have checked that your toolchain is okay and installation still fails, please provide your `/usr/local/impress/node_modules/metarhia-jstp/builderror.log`.

**Comment by aqrln** [comment]
@dmytro-khara can I close the issue or you still can't install JSTP?

**Comment by dmytro-khara** [comment]
@aqrln you can close the issue
