### ISSUE TITLE
Update vulnerable dependencies

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/jstp#330]
See `moment` https://github.com/metarhia/jstp/network/dependencies#37208224
@aqrln @belochub @nechaido

**Comment by belochub** [comment]
It is impossible to update this dependency because `metarhia-jstp` does not depend on it directly, it is listed in the dependencies of the latest version of `gitbook` package, so the only way to resolve this issue is to wait until `gitbook` developers will update dependencies in their package.

**Comment by tshemsedinov** [comment]
Thanks for investigation this issue

**Comment by aqrln** [comment]
For posterity, the subject dependency was removed in #336.
