### ISSUE TITLE
Reconnecting to existing sessions

### ISSUE THREAD

**Issue by aqrln** [metarhia/jstp#35]
Now we have an abstraction of session but it isn't used anywhere. There must be a possibility to connect to an existing session specifying its ID in handshake packet. When a client loses its connection, it must reconnect to the session automatically and transparently.

**Comment by aqrln** [comment]
In order to implement this, we should change the format of `handshake` packets so it is not strictly bound to login and password but rather allows to specify the authentication strategy (login/password, anonymous, existing session etc). I am working on an implementation currently.

**Comment by belochub** [comment]
Closed in https://github.com/metarhia/jstp/commit/4d600f4587238f0a8165bbb812e4570c5a9f01c7.
