### ISSUE TITLE
ExpiringMap bug

### ISSUE THREAD

**Issue by ykolomiets** [metarhia/jstp#413]
Hi, guys!
I think you have a bug here.
After removing an element from a map, you don't remove the same key from _deletionTimes,
so if you set new element with the same key it will be removed on next _purge. If set only unique keys this is not critical, but _deletionTimes just grows

https://github.com/metarhia/jstp/blob/3f5d89066956ab56360c4ff173c096d763cf375a/lib/common.js#L126-L133

**Comment by belochub** [comment]
Hi, thanks for reporting this!
I see where the problem is and what the possible negative effects are, fix is on the way.
