### ISSUE TITLE
Bidirectional RPCs

### ISSUE THREAD

**Issue by ykolomiets** [metarhia/jstp#419]
Does jstp support bidirectional RPCs?

**Comment by ykolomiets** [comment]
@tshemsedinov, @belochub, @aqrln anybody?

**Comment by belochub** [comment]
Hi, yeah, we do support bidirectional RPCs, you can define an [`application`](https://metarhia.github.io/jstp/api/client/#clientapplication) field on your [`client`](https://metarhia.github.io/jstp/api/client/) with client-side RPC methods, and call them on server-side `connection` via [`connection.callMethod()`](https://metarhia.github.io/jstp/api/connection/#connectioncallmethodinterfacename-methodname-args-callback) or by first inspecting the interfaces using [`connection.inspectInterface()`](https://metarhia.github.io/jstp/api/connection/#connectioninspectinterfaceinterfacename-callback) and then using the obtained [`RemoteProxy`](https://metarhia.github.io/jstp/api/remote-proxy/) instances to make the needed calls.

**Comment by ykolomiets** [comment]
Thanks a lot
