### ISSUE TITLE
Реализовать api.vm для браузера

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/JSTP#6]
* api.vm.createContext
* api.vm.createScript
* api.vm.isContext
* api.vm.runInDebugContext
* api.vm.Script
* script.runInContext и api.vm.runInContext
* script.runInNewContext  и api.vm.runInNewContext
* script.runInThisContext и api.vm.runInThisContext

**Comment by sun1x** [comment]
Сделал это в отдельном [репозитории](https://github.com/sun1x/vm-browser)
Работает во всех современных браузерах начиная с Internet Explorer 8

Есть один нюанс
В старых версиях Internet Explorer `eval` отсутствует в `iframe`. Вместо него используется `execScript`, который не возвращает результат последнего выполняемого выражения.
Можно обойти это кинув результат в контекст. Пример:
```javascript
var context = vm.createContext();

 // Usually it will print "3", but old versions of IE will print "undefined"
var code = 'var a = 1; var b = 2; a + b;';
console.log(vm.runInContext(code, context));

// In old versions of IE we can do something like this
code = 'var a = 1; var b = 2; window.result = a + b;';
vm.runInContext(code, context);
console.log(context.result);
```

И вопрос
Нам критичен `vm.runInDebugContext`? Если не ошибаюсь, не выйдет написать аналог.

**Comment by tshemsedinov** [comment]
Для `mv.runInDebugContext` делаем заглушку, выводим просто сообщение в консоль, что не поддерживается. Совсем старые браузеры не нужно поддерживать, очень страшных костылей и конструкций лучше избежать, а выводить в консоль, что браузер не найден.
