### ISSUE TITLE
Build should fail when native extension can't be built on CI

### ISSUE THREAD

**Issue by belochub** [metarhia/JSTP#63]
I checked CI logs today and found out that our native extension was not built for a while now because of compilation errors. It caused no errors in CI, because it just used JavaScript implementation of parser which is working fine.
I think that we maybe need to add some environment variable check for CI so that tests won't pass when native extension can't be built.

**Comment by aqrln** [comment]
@belochub yeah, that's quite easy to check. The variable is `process.env.TRAVIS`.
