### ISSUE TITLE
Предложения по реализации binary stream

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/JSTP#7]
Нам нужно сделать JSTP совместимым с передачей бинарных данных в режиме стриминга, по частям, блоками, как торренты. Это не срочно, но жду ваших предложений, @aqrln и @RayGron Это может быть отдельный проект, по трансляции и ретрансляции видеопотока в двоичном виде через пиринговую сеть.

**Comment by aqrln** [comment]
Superseded by #34
