### ISSUE TITLE
Impossibility to catch `error` event arising in connections during handshake

### ISSUE THREAD

**Issue by belochub** [metarhia/JSTP#76]
At the moment, when a server is being created and someone sends incorrect first packet (which must be handshake, but can be anything), node will crash with message "Unhandled 'error' event", even if there is an `error` event listener for this server.
That happens because we forward `error` event listener from transport to server (as `connectionError`) only after handshake was processed.
I guess possible fix will be to forward `error` event to server on connection creation.

**Comment by belochub** [comment]
This bug seems to be critical, because it can cause server downtime by spamming incorrect packets on connection.

**Comment by aqrln** [comment]
@belochub can you check if https://github.com/metarhia/JSTP/pull/78 fixes the issue?
