### ISSUE TITLE
#81 discussion follow-up and request for comments

### ISSUE THREAD

**Issue by aqrln** [metarhia/jstp#85]
After some discussion with @belochub about https://github.com/metarhia/JSTP/pull/81 we came to conclusion that we don't actually need sent messages count in both handshake request and response, only received ones.

/cc @lundibundi @Gagnant @GYFK @lidaamber

**Comment by lundibundi** [comment]
Ok with me, that was actually the question when i asked about them.

**Comment by aqrln** [comment]
@lundibundi thanks for the feedback and for noticing a redundancy in the specs we prepared.
@Gagnant we need you approval to do this since you're a member of Session WG too and we don't want to break the iOS client :)

**Comment by Gagnant** [comment]
Also agree with the changes

**Comment by aqrln** [comment]
@Gagnant great.

Hence I propose to update the handshake format like this:

| Request | Response |
| --- | --- |
| `{ handshake: [0, 'appName'], session: ['sessionId', received_count] } ` | `{ handshake: [0], ok: received_count }` |

**Comment by belochub** [comment]
LGTM, can't wait to start using this feature.

**Comment by Gagnant** [comment]
LGTM

**Comment by lundibundi** [comment]
LGTM

**Comment by aqrln** [comment]
Refs: https://github.com/metarhia/JSTP/issues/35
