### ISSUE TITLE
Неоднозначність декодування записів

### ISSUE THREAD

**Issue by anxolerd** [metarhia/JSTP#9]
# Проблема
За основу взято [опис RecordData](https://github.com/metarhia/JSTP#record-data):

```js
var metadata = {firstName: 'string',  lastName: 'string'};
var data = ['John', 'Doe'];
var obj = api.jstp.decode(data, metadata);
```

Проблема полягає у тому, що у загальному випадку, ми не можемо гарантувати, що правильним ключам поставляться у відповідність правильні значення. Тобто, для описаного прикладу можливі два варіанти:

```js
// Варіант 1
console.dir(obj);  // { firstName: 'John', lastName: 'Doe' }

// Варіант 2
console.dir(obj);  // { firstName: 'Doe', lastName: 'John' }
```

Причина такої неоднозначності у тому, що [специфікація JS не визначає порядок ключів у об'єкті](http://www.ecma-international.org/ecma-262/5.1/#sec-12.6.4), залишаючи на розсуд тих, хто реалізує її.

# Пропозиції

Необхідно змінити [формат метаданих]( https://github.com/metarhia/JSTP#record-metadata) таким чином, щоб він включав послідовність полів. 

## Варіант 1. Додаткове поле в метаданих
```js
{
    firstName: 'string',  
    lastName: 'string',
    __order__: ['firstName', 'lastName'],
};
```

## Варіант 2. Метадані як список

```js
[
    ['firstName', 'string'],
    ['lastName', 'string'],
]

// або

[
    { field: 'firstName', type: 'string'},
    { field: 'lastName', type: 'string'},
]
```
---
Із урахуванням https://github.com/metarhia/JSTP/issues/2, я схиляюся до видозміненого першого варіанту (за основу взято [коментар від 29 березня 2016 р](https://github.com/metarhia/JSTP/issues/2#issuecomment-202968413)):

```js
{
  firstName: [ /* ... */ ],
  lastName: [ /* ... */ ],
  __meta__: {
    cache: { /* ... */ },
    order: ['firstName', 'lastName'],
  }
}
```

**Comment by tshemsedinov** [comment]
Везде все однозначно. Эти костыли не нужны. Синтаксис JSTP предполагает, что порядок полей всегда совпадает. Это вопрос реализации.

**Comment by aqrln** [comment]
В V8 порядок полей сохраняется (а хак с парсингом при помощи интерпретатора мы используем именно там), а где нет — можно и нужно парсить вручную. А в своём парсере нет никакой проблемы сохранять порядок. Так что солидарен с @tshemsedinov.
