### ISSUE TITLE
Incorrect term usage (s/packet(s)/message(s))?

### ISSUE THREAD

**Issue by aqrln** [metarhia/jstp#91]
It is not technically correct to say "JSTP packets" since packets are the PDUs of layer 3 protocols. Layer 5 protocols don't have a standardized concept of PDU (and what they transfer is simply referred to as data) but in practice their data units are commonly called messages.

**Comment by aqrln** [comment]
ping @metarhia/jstp-core

**Comment by belochub** [comment]
Yes, I agree with that, we should change this misuse of terns.

**Comment by lundibundi** [comment]
Completely agree on this one, with this https://github.com/metarhia/jstp-java/commit/8671892d4ece4e983a952ae61d0bb2e5a31fe563 java version uses 'message' throughout its codebase.
